### ISSUE TITLE
Data analytics 1.9

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3717]
- [X] track events only from production builds to `stable.log`, all others to `develop.log`
- [ ] session-end is not sent on desktop app close: _Probably no problems after implementing Beacon API_
- [X] update docs
- [X] track suite-ready on initial run
- [X] analyse new events [Notion](https://www.notion.so/satoshilabs/Analytics-overview-3b49d66235e044928b79954d3a4ac8ff)
- [X] add new events, extend and fix existing ones 
  - the rest can be done in 1.10 analytics

**Comment by tomasklim** [comment]
After discussion with @tsusanka:
- Analytics tracking destination will not be determined by hostname anymore
  - Production builds will send its analytics events to `stable.log` 
    - This includes staging (to achieve exactly the same behaviour on prd and stg)
  - Events from all other builds except the ones running on `localhost` will be sent to `develop.log`
  - Events from `localhost` are not sent anywhere (remains the same)
  

```
  const getUrl = () => {
    const hostname = getLocationHostname();
    const environment = getEnvironment();
    const base = `https://data.trezor.io/suite/log/${environment}/`;
    if (process.env.CODESIGN_BUILD) {
        return `${base}/stable.log`;
    }
    // no reporting on localhost
    if (hostname === 'localhost') {
        return;
    }
    return `${base}/develop.log`;
  };
```

- Analytics events will be sent using [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API), instead of Fetch API
> The Beacon API is used to send an asynchronous and non-blocking request to a web server. The request does not expect a response. Unlike requests made using XMLHttpRequest or the Fetch API, the browser guarantees to initiate beacon requests before the page is unloaded and to run them to completion.
  - This requires adding `POST` request method to analytics server because `navigator.sendBeacon` sends data using `POST` request method but before we used `fetch` with `GET` request method.

**Comment by tomasklim** [comment]
Changing HTTP request method from `GET` to `POST` is postponed as there is problem with `Allowed HTTP Methods` settings in AWS s3.

**Comment by tsusanka** [comment]
@alex-jerechinsky I would close this issue as a "won't fix" since it will need a complete overhaul to make it work. Also @alex-jerechinsky maybe let's remove the "session length" metric in Tablue completely? So it does not confuse readers.

**Comment by bosomt** [comment]
is there anything that need to be tested on our side ?

**Comment by tomasklim** [comment]
@bosomt I updated docs, you can read it and it will probably prepare you a little bit for testing as there are described ways how to test it. We still did not define an exact process how to test this feature. 

However, for now you can check that:
-  events are sent to correct endpoints (see docs)
-  `suite-ready` event is sent when you finish onboarding and also when you launch initialised app
-  `transaction-created` is sent when you sent/copy/download/replace a transaction

There are other changes, you can find them in the changelog in the docs. 

https://github.com/trezor/trezor-suite/blob/f0654cc6ef290c203a1858e87646240d6516ebfb/docs/misc/analytics.md

**Comment by sorooris** [comment]
- [x] track events only from production builds to stable.log, all others to develop.log :x: 

  - seems that actions on staging are not logged in /suite/log/desktop/staging.log (which is empty) and are instead logged in /suite/log/desktop/stable.log - needs to be verified
- [x] session-end is not sent on desktop app close -  :x: still not being sent
- [x] update docs -  :x: to be finalized
- [x] track suite-ready on initial run - sent correctly :heavy_check_mark: 
- [x] analyse new events Notion
   - c_v: version of analytics :heavy_check_mark: 
   - c_type: type of tracked event :heavy_check_mark:
   - c_commit: current revision of app :heavy_check_mark:
   - c_instance_id: until user does not wipe storage, the id is still same :heavy_check_mark:
   - c_session_id: id changed on every launch of app :heavy_check_mark:
- [x] add new events, extend and fix existing ones -  :x: too vague, can not verify
- [x] the rest can be done in 1.10 analytics -  :x: too vague, can not verify

**Comment by sorooris** [comment]
> However, for now you can check that:
> 
> * events are sent to correct endpoints (see docs)
> * `suite-ready` event is sent when you finish onboarding and also when you launch initialised app
> * `transaction-created` is sent when you sent/copy/download/replace a transaction

:x: events are sent to correct endpoints (see above https://github.com/trezor/trezor-suite/issues/3717#issuecomment-857692597)
:heavy_check_mark: `suite-ready` event is sent when you finish onboarding and also when you launch initialised app
:heavy_check_mark: `transaction-created` is sent when you sent/copy/download/replace a transaction

**Comment by tomasklim** [comment]
>  seems that actions on staging are not logged in /suite/log/desktop/staging.log (which is empty) and are instead logged in /suite/log/desktop/stable.log - needs to be verified ❌

That is correct. Production build is available on staging. ✅ 

> session-end is not sent on desktop app close - ❌ still not being sent

Yep, it was postponed. ✅
