### ISSUE TITLE
Suite microsite FE product improvements

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4120]
**Is your feature request related to a problem? Please describe.**
We have brought a couple product mistakes into the microsite's design and we'd love having them fixed.

**Describe the solution you'd like**
Improved design: [Zeplin](https://zpl.io/VqNJxZJ)

Improvements:
1. Correct XRP logo. Please replace the incorrect XRP logo with the correct one 
<img width="29" alt="image" src="https://user-images.githubusercontent.com/88533514/128511139-8d4f55df-9cd2-4785-a6c6-29e776e40932.png">

2. Correct XRP naming. Please replace "Ripple" with "XRP" like in the design below:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/88533514/128511308-12094dff-63a4-4fa4-a010-d41401d08489.png">

3. Remove "Kč" from FIAT units. As per [the new design](https://zpl.io/VqNJxZJ):
<img width="693" alt="image" src="https://user-images.githubusercontent.com/88533514/128664120-38d51a5b-94c6-4c71-818c-a3fb0773e7ad.png">

4. Change copy of the last fold. The green part of it looks like it should be interactive and show specific new features. It doesn't. Pls replace the wording with a shorter "Dozens of features to discover. Try suite now." with no green parts (all in #404040)
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/88533514/128512414-0bfe0b8f-1a97-40c8-9703-45a67c37fcf8.png">

**Describe alternatives you've considered**
This whole microsite needs a lot more love, but as a quick win, this should work fine.

**Comment by marekrjpolak** [comment]
Should be fixed here: https://suite.corp.sldev.cz/suite-web-landing/fix/4120-landing-page-improvements/

**Comment by tomasklim** [comment]
Nitpick @Hermez-cz:
> Remove "Kč" from FIAT units. As per the new design:

- The first image `Desktop app` still has Kč.
- `Native altcoin support` image has numbers in Kč. If we have it in dollars, then Ethereum Classic would have space for the currency symbol.

**Comment by Hermez-cz** [comment]
@tomasklim Thank you! Especially for checking precisely against reality and not just the tiny incomplete spec above.
- We have missed the first "hero" image in design, sorry about that. > We will prepare corrected graphics ASAP.
- You're right, just hiding currency symbol behind the edge doesn't solve the correct FIAT price fully. > I will provide a more detailed spec to this as soon as I will find out preferred FIAT currency formats of our users from the research team.

_What's the best practice now please? We can either close this issue as successful, as the spec above has been fulfilled. Or leave it open and improve the spec... I'm ok with both and don't want to create mess against rules here._

**Comment by tomasklim** [comment]
@Hermez-c
> What's the best practice now please? We can either close this issue as successful, as the spec above has been fulfilled. Or leave it open and improve the spec... I'm ok with both and don't want to create mess against rules here.

I think that it is best to open a new one and leave there a note that it is a continuation/improvement of this one. Otherwise, it would be a mess not only for us but especially for QA.

**Comment by Hermez-cz** [comment]
> @Hermez-c
> 
> > What's the best practice now please? We can either close this issue as successful, as the spec above has been fulfilled. Or leave it open and improve the spec... I'm ok with both and don't want to create mess against rules here.
> 
> I think that it is best to open a new one and leave there a note that it is a continuation/improvement of this one. Otherwise, it would be a mess not only for us but especially for QA.

Thank you, I absolutely agree. Will create a new issue as soo as the more detailed spec will be ready.

**Comment by bosomt** [comment]
4x **QA OK**

Suite dev master commit f9ecf819ac9cc809aa78295793c065c508f74e72

**Comment by bosomt** [comment]
> > @Hermez-c
> > > What's the best practice now please? We can either close this issue as successful, as the spec above has been fulfilled. Or leave it open and improve the spec... I'm ok with both and don't want to create mess against rules here.
> > 
> > 
> > I think that it is best to open a new one and leave there a note that it is a continuation/improvement of this one. Otherwise, it would be a mess not only for us but especially for QA.
> 
> Thank you, I absolutely agree. Will create a new issue as soo as the more detailed spec will be ready.

Thank you @Hermez-cz  approving this issue and we will wait for new issue :)
