### ISSUE TITLE
Missing label in transaction history export

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#4604]
**Describe the bug**
There is a missing label in transaction history export (missing in JSON, PDF and csv formats). 

**Steps to reproduce:**
1. Enable labeling (google)
2. Create labels
3. Export
4. Check 

**Info:**
 - Suite version: web 21.12.1 (4a5547dd0d5c3608718f736e2f34638dc427e2d4)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
 - Labeling: Google

**Expected result:**
All labels will be correctly displayed in exports.

**Actual result:**
A label is missing.

**Screenshots:**
Screenshots presented here - the missing labels are all on ONE transaction 92d33f1cc5625499d52ebce54dbb0b23a5d53f439bbb6ff6d637e99dd3a5cfb1 BUT @bosomt has also had a missing label, on a different wallet.
(mnaumissing label is not present in csv export)
![image](https://user-images.githubusercontent.com/58593111/144592936-68fdd414-57e8-462e-a9d8-80048bd64a00.png)

(labelk label is missing from JSON export)
![image](https://user-images.githubusercontent.com/58593111/144593269-8dff1be2-abb9-466c-90cd-a9ad7159ae3a.png)
![image](https://user-images.githubusercontent.com/58593111/144593502-493d1cfe-004c-4cb7-80c5-d57b663a6c30.png)

(mnaumissing label is not present in PDF export)
![image](https://user-images.githubusercontent.com/58593111/144593457-a4614ed5-c7d2-4fd2-9982-669e49f7d6bf.png)

**Comment by wendys-cats** [comment]
@STew790 reported that he has also reproduced the issue, and it looks like the second transaction (the second newest) or second label (from the top) is always missing the label in export.

**Comment by wendys-cats** [comment]
Production also displays this bug :D 
(mnaudva label missing in csv export)
![image](https://user-images.githubusercontent.com/58593111/144594347-07707e1b-66b2-4544-9b95-6402db6bce2e.png)

**Comment by bosomt** [comment]
same results with `Saving labels locally`

<img width="699" alt="Screenshot 2021-12-03 at 12 04 23" src="https://user-images.githubusercontent.com/31506317/144594653-c8154871-fec8-4cef-8684-bdb4f45884fb.png">

<img width="785" alt="Screenshot 2021-12-03 at 12 04 02" src="https://user-images.githubusercontent.com/31506317/144594808-1317eb64-b627-4214-8ace-24a69753c21c.png">

**Comment by bosomt** [comment]
looks like issue was fixed in current dev build 
/probably thanks to  RangeError: Maximum call stack size exceeded #5072 /
@wendys-cats please check/confirm 


**Info:**
 - Suite version: web 22.3.0 (c888b3c75010889499e52033fec908ee28045c95)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.4 regular

**Comment by wendys-cats** [comment]
Looks fixed for me as well! Closing the issue, will reopen if it happens again.
 
**Info**
 - Suite version: web 22.4.0 (cd474f1858fdb089f8c5cdae7ffabd6e97a470d4)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.4 regular

**Comment by wendys-cats** [comment]
Reopening the issue, missing label in transaction export has been spotted again

**Comment by STew790** [comment]
Unfortunately, still happening.

**Info:**
 - Suite version: desktop 22.5.2 (a4ec55219fe123c0bb073d4b8338041eb176add4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by STew790** [comment]
This is still happening, unfortunately.

**Info:**
 - Suite version: desktop 22.6.1 (8d37e21edabe10ea6b6991f5e3a338e3464925e1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by STew790** [comment]
Still present.

**Info:**
 - Suite version: desktop 22.7.1 (b82987dd15049a1578bbeb4705d32b6f1edb7893)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment]
**QA OK**

so far it looks fixed, but we will try to replicate this issue before we approve it
I was not able to replicate it in Standard Bitcoin wallet, 10 labels created, Dropbox used.
PDF and CSV export contains all 10 labels in correct order.


**Info:**
 - Suite version: web 22.9.0 (4d282475dccf0c52a0094e9b024fce5ad7c54e53)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 Bitcoin-only (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31
